name: UI PR

on:
  pull_request:
    branches: main

jobs:
  ui-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ui
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.1"

      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
      - name: yarn install
        run: yarn install --immutable

      - name: Run Tests
        run: yarn test

      - name: "Test"
        run: npx vitest --coverage.enabled true

      - name: "Report Coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ui
          json-summary-path: html/ui/coverage-summary.json
          json-final-path: html/ui/coverage-final.json

      - name: Post the knip results
        run: yarn knip --max-issues=${{ vars.KNIP_MAX_ISSUES }}

      - name: Run ESLint
        run: yarn lint --max-warnings ${{ vars.LINT_MAX_WARNINGS }}

      - name: Danger
        if: github.actor != 'dependabot[bot]'
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
